server:
  port: 9001
  tomcat:
    connection-timeout: 2s # default 20s, ??????? TCP ??? ???? ??? HTTP ??? ???? ??? ??? ???? ?? ( ??? ?? ??? ???? ? ??? ??.)
    keep-alive-timeout: 15s # ??? HTTP ??? ???? ?? ??? ???? ??? ??
    threads: # ??? ??? ??? ???? ?? ??? ???? ??? ?? ??? ??? ?? ??? ? ??
      max: 50 # ?? ?? ?? ??? ? ??
      min-spare: 5 # ??? ?? ?? ?????? ??? ??? ? ( ??? ??? ? ? ??? ??? ?? ??? ???? ?? ??? )


spring:
  application:
    name: catalog-service

polar:
  greeting: Welcome to the local book catalog!
